### PR TITLE
Changed from Python 2 to python 3 and fixed some minor errors regardi…

### PR DESCRIPTION
**Pull request by Srivastava57Harsh**
…ng Gi (version) and Gtk

### CODE REVIEW

**Comment by Aniket21mathur** [comment]
Thanks. Reviewed. The Python 2 to Python 3 changes are not complete. Please see the [guide](https://github.com/sugarlabs/sugar-docs/blob/master/src/python-porting-guide.md) again. You have missed

- Change exec value in activity.info from sugar-activity to sugar-activity3

**Comment by Srivastava57Harsh** [comment]
> Thanks. Reviewed. The Python 2 to Python 3 changes are not complete. Please see the [guide](https://github.com/sugarlabs/sugar-docs/blob/master/src/python-porting-guide.md) again. You have missed
> 
> * Change exec value in activity.info from sugar-activity to sugar-activity3

was this the only change i needed as i couldn't anything else

**Comment by Aniket21mathur** [comment]
@Srivastava57Harsh sorry I didn't understand your question.

**Comment by Srivastava57Harsh** [comment]
> @Srivastava57Harsh sorry I didn't understand your question.

I mean I have changed the exec value now what do i need to do

**Pull request merged**
