### PR TITLE
Changing the value of "exec"

### PR DESCRIPTION
**Pull request by Srivastava57Harsh**

### CODE REVIEW

**Comment by Hrishi1999** [comment]
`saber.py` is not ported to python3 (look at the print statement). Please also test your changes before and after the port and make sure that the activity works.

**Comment by Srivastava57Harsh** [comment]
> `saber.py` is not ported to python3 (look at the print statement). Please also test your changes before and after the port and make sure that the activity works.

Sir i have made the changes , please refer to this link 
https://github.com/sugarlabs/feliz-navidad-activity/commit/8c14dd2162811f115ba2f693e803373727e6c680

**Comment by Srivastava57Harsh** [comment]
> `saber.py` is not ported to python3 (look at the print statement). Please also test your changes before and after the port and make sure that the activity works.

I had changed saber.py earlier , and i assured that the activity works

**Comment by Hrishi1999** [comment]
You should add this change as a commit in https://github.com/sugarlabs/feliz-navidad-activity/pull/5 and close this pull request.

**Pull request closed without merging**
